FROM fedora:39

RUN dnf makecache
RUN dnf -y install "https://kojipkgs.fedoraproject.org//packages/trafficserver/9.2.4/1.fc39/$(arch)/trafficserver-9.2.4-1.fc39.$(arch).rpm"

COPY remap.config /etc/trafficserver/remap.config

CMD ["traffic_server"]
